### ISSUE TITLE
Data 

### ISSUE THREAD

**Issue by jiz322** [HuiyuanXie/tiage#1]
In class WikiDataLoader, it retrieves targets, sentences, next_sentences (line58). 
I saw the data files in the anno folder, but none of them provide these columns together.

Did I miss something? Or should I process the data myself?

Thank you!

**Comment by jiz322** [comment]
What is the first col in anno_train_all_dialogs.tsv?

**Comment by HuiyuanXie** [comment]
Hi @jiz322 thanks for your interest in the TIAGE dataset.

To answer your questions: 
1. WikiDataLoader is used to train a BERT classifier to predict topic shifts on the wiki-727k data. This is part of the exploratory experiments that I did on the wiki-727k data, which does not directly related to the TIAGE data/benchmarks that are highlighted in the paper. The anno data only consists of dialog data originally from PersonaChat, so does not contain any data from wiki-727k. I could share all the scripts that I used to train the BERT classifier on wiki-727k with you if that helps. 
2. The first column in the anno_train_all_dialogs.tsv file is the index of each utterance in a dialog. You will notice that the index starts from 0 and finishes with a number x where x > 0. This indicates that there are x+1 utterances in this dialog concerned. Utterances with an index 0 also indicates that this is a new dialog instance / this utterance is the first utterance of the new dialog. I hope this info helps.

**Comment by jiz322** [comment]
This is helpful. Thank you! 

I am searching for classifier/data for detecting the shift of topic, so I am focusing more on the classifier part in the paper.
You mentioned there are other scripts or files for the classifier. I wish I can get them.
